name: SAM CI/CD Deploy

on:
  #push:
    #branches:
      #- main  # deploy test automatically
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # only for main branch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Validate template
        run: sam validate

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Build SAM app
        run: sam build --use-container

      - name: Deploy SAM app to Test
        run: |
          sam deploy \
            --stack-name visitor-counter-test \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --s3-bucket harmon-portfolio-backend-assets
