name: SAM CI/CD Deploy

on:
  push:
    branches:
      - main  # deploy test automatically
  workflow_dispatch:  # allows manual triggers for prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # only for main branch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN_TEST }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Install SAM CLI
        run: |
          pip install --upgrade pip
          pip install -r visitor_counter/requirements.txt
          pip install aws-sam-cli

      - name: Validate template
        run: sam validate

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Clear SAM config
        run: rm -rf ~/.aws-sam/config

      - name: Build SAM app
        run: sam build --use-container

      - name: Deploy SAM app to Test
        env:
          SAM_PROFILE: ''
          AWS_PROFILE: ''
          SAM_CONFIG_DIR: /tmp/samconfig
        run: |
          sam deploy \
            --stack-name visitor-counter-test \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --resolve-s3
          

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-test
    if: github.event_name == 'workflow_dispatch'  # manual trigger only

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SAM CLI
        run: |
          pip install --upgrade pip
          pip install aws-sam-cli

      - name: Validate template
        run: sam validate

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app to Prod
        run: sam deploy --stack-name visitor-counter-prod --no-confirm-changeset
